### PR TITLE
first branch off

### PR DESCRIPTION
**Pull request by Stalkakuma**

### CODE REVIEW

**Comment by Stalkakuma** [comment]
Looks like ESlint was a great success, unlike myself.

**Comment by Stalkakuma** [comment]
Imported ESlint into our workflow successfully.

**Comment by Stalkakuma** [comment]
1. Outlined components
2. Added Router
3. Added Mock Logo
4. Added Mock Header
5. Added Mock Navigation
6. Minor content

**Comment by Stalkakuma** [comment]
1. Added a Responsive navbar from react-bootstrap
2. Deleted some unnecessary components

**Comment by Stalkakuma** [comment]
1. Added a shoddy search bar (to be continued)
2. More pages outlined
3. Played around with CSS

**Review by jlemesh — APPROVED** [review]

**Pull request merged**
